### ISSUE TITLE
Version 2 still in the works?  

### ISSUE THREAD

**Issue by Avrution** [IpsumLorem16/Simple-IP-Camera-Viewer#3]
Came across your post from reddit a while back mentioning version 2 and wondered if it was still planned?  

The current extension I use isn't under development anymore and is becoming more dated - https://addons.mozilla.org/en-US/firefox/addon/myipcam-for-ip-cameras/

Have been hoping for a new solution.

**Comment by IpsumLorem16** [comment]
Hello, yes it is still in development. but not ready for a  little while,

 I have been using it myself for a long time. but it needs a few more bits before it is usable by other people.

Mainly just the layout creator, which is a work in progress. 

Can I ask what are the main features you need for this extension?

**Comment by Avrution** [comment]
Main features are multiple cameras per page, ideally from a popup window.  

PTZ controls - really just PT.

Ability to change the size of the window for the camera - both multiple and single.  Currently, being limited to a 640x480 view unless I want scrollbars is annoying.

**Comment by IpsumLorem16** [comment]
The layout is customisable for the user. very similar to this [CSS Grid generator.](https://cssgrid-generator.netlify.app/), but easier to use.

The grid will be 100% height and width of the browser window.  That can also be fullscreened with f11. 

PTZ controls, I don't know how to implement this currently. If you know the URL for each direction (grab it from the cameras builtin web-page when pressing a button while looking in the network tab of the devtools). Then you can add this manually using the "add button" feature > selecting an Icon > and positioning it on the camera. (buttons fade out unless mouse is moved over the camera so it does not block the view)

There will be the option to continue hitting that URL if the button is held, so it will mimic the native webpage camera controls.

Those are the two main things I need to finish: buttons and layout creator before this extension is released. Other features I will add on updates.

**Comment by IpsumLorem16** [comment]
Closing issue. Feel free to create a new one if there any more questions.
